/*
   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/* Attributes State Machine */
enum
{
    IDX_SVC,

    IDX_CHAR_SCORE,
    IDX_CHAR_VAL_SCORE,

    IDX_CHAR_FLAG,
    IDX_CHAR_VAL_FLAG,
    
    IDX_CHAR_FLAG_SIMPLE_READ,
    IDX_CHAR_VAL_FLAG_SIMPLE_READ,
    
    IDX_CHAR_FLAG_MD5,
    IDX_CHAR_VAL_FLAG_MD5,

    IDX_CHAR_FLAG_WRITE_ANYTHING,
    IDX_CHAR_VAL_FLAG_WRITE_ANYTHING,

    IDX_CHAR_FLAG_WRITE_ASCII,
    IDX_CHAR_VAL_FLAG_WRITE_ASCII,

    IDX_CHAR_FLAG_WRITE_HEX,
    IDX_CHAR_VAL_FLAG_WRITE_HEX,

    IDX_CHAR_FLAG_SIMPLE_WRITE2_READ,
    IDX_CHAR_VAL_FLAG_SIMPLE_WRITE2_READ,

    IDX_CHAR_FLAG_SIMPLE_WRITE2,
    IDX_CHAR_VAL_FLAG_SIMPLE_WRITE2,

    IDX_CHAR_FLAG_BRUTE_WRITE,
    IDX_CHAR_VAL_FLAG_BRUTE_WRITE,

    IDX_CHAR_FLAG_READ_ALOT,
    IDX_CHAR_VAL_FLAG_READ_ALOT,
    
    IDX_CHAR_FLAG_NOTIFICATION,
    IDX_CHAR_VAL_FLAG_NOTIFICATION,
    IDX_CHAR_CFG_FLAG_NOTIFICATION,

    IDX_CHAR_FLAG_INDICATE_READ,
    IDX_CHAR_VAL_FLAG_INDICATE_READ,

    IDX_CHAR_FLAG_INDICATE,
    IDX_CHAR_VAL_FLAG_INDICATE,
    IDX_CHAR_CFG_FLAG_INDICATE,
 
    IDX_CHAR_FLAG_NOTIFICATION_MULTI,
    IDX_CHAR_VAL_FLAG_NOTIFICATION_MULTI,
    IDX_CHAR_CFG_FLAG_NOTIFICATION_MULTI,

    IDX_CHAR_FLAG_INDICATE_MULTI_READ,
    IDX_CHAR_VAL_FLAG_INDICATE_MULTI_READ,

    IDX_CHAR_FLAG_INDICATE_MULTI,
    IDX_CHAR_VAL_FLAG_INDICATE_MULTI,
    IDX_CHAR_CFG_FLAG_INDICATE_MULTI,
    
    IDX_CHAR_FLAG_MAC,
    IDX_CHAR_VAL_FLAG_MAC,

    IDX_CHAR_FLAG_MTU,
    IDX_CHAR_VAL_FLAG_MTU,
    
    IDX_CHAR_FLAG_WRITE_RESPONSE,
    IDX_CHAR_VAL_FLAG_WRITE_RESPONSE,

    IDX_CHAR_FLAG_HIDDEN_NOTIFY,
    IDX_CHAR_VAL_FLAG_HIDDEN_NOTIFY,
   
    IDX_CHAR_FLAG_CRAZY,
    IDX_CHAR_VAL_FLAG_CRAZY,

    MAIN_IDX_CHAR_TOKEN,
    MAIN_IDX_CHAR_TOKEN_VAL,
    MAIN_IDX_CHAR_TOKEN_CFG,

    MAIN_IDX_CHAR_AUTH,
    MAIN_IDX_CHAR_AUTH_VAL,
    MAIN_IDX_CHAR_AUTH_CFG,

    HRS_IDX_NB,
};


typedef enum {
    FLAG_SIMPLE_READ, 
    FLAG_DEVICE_NAME_MD5, 
    FLAG_DEVICE_NAME_ATTR, 
    FLAG_WRITE_ANY, 
    FLAG_WRITE_ASCII, 
    FLAG_WRITE_HEX, 
    FLAG_WRITE_DECIMAL_HANDLE, 
    FLAG_WRITE_FUZZING, 
    FLAG_READ_MANY, 
    FLAG_SINGLE_NOTIFICATION, 
    FLAG_SINGLE_INDICATION, 
    FLAG_MULTIPLE_NOTIFICATION, 
    FLAG_MULTIPLE_INDICATION, 
    FLAG_SPOOF_MAC, 
    FLAG_CHANGE_MTU, 
    FLAG_WRITE_RESPONSE, 
    FLAG_HIDDEN_NOTIFICATION, 
    FLAG_MULTIPLE_PROPERTIES, 
    FLAG_TOKEN,
    FLAG_AUTH
} FlagIndex;
